// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Expression = 1,
  AddExpr = 2,
  MulExpr = 3,
  Term = 4,
  Number = 5,
  String = 6,
  Boolean = 7,
  Variable = 8,
  Identifier = 9,
  ParenExpr = 10,
  MulOperator = 11,
  AddOperator = 12
